# Git Installation & GitHub Account {#git}

## Git

Check to see if your computer already has git:

- Open RStudio
- In the terminal, run the following command:

`which git`

If `git` is already installed, the return to the above command should return a filepath (ex: `/usr/local/bin/git`). 

- If there is no response, download and install `git` from here: [git-scm.com/downloads](https://git-scm.com/downloads). Select the default settings within the prompts **except** the default to **master** branch. This branch is being phased out, so select the option that let's you select alternative branches (ex: main).

## GitHub

GitHub is a internet based code hosting platform for collaboration and [version control](https://www.atlassian.com/git/tutorials/what-is-version-control#:~:text=Version%20control%2C%20also%20known%20as,to%20source%20code%20over%20time.). GitHub lets you (and others) work together on projects.

Navigate to [github.com](https://github.com/), and create an account! Please use either your work or personal email account. You can add several emails to your account, and assign a particular email as the primary email for the account. 

Review this article on choosing a GitHub username: [happygitwithr.com/github-acct.html](happygitwithr.com/github-acct.html). 
