# Code of Conduct {#codeofconduct}

The Center of Conservation Biology's Code of Conduct adapted from [@Perry_2018]


## We are committed to working as a team. 

All aspects of our professional contributions to the project are discussed and agreed upon together, and all tasks - although they might be led by individual team members - are developed through collaborative practice. Devotion to supporting the team, working as a team player, providing constructive critique to your team members, and respecting the interests of the team as a successful working group (without compromising their safety or security, as described below), are paramount.

## We are committed to prioritizing and championing the people and communities that host us. 

Our work is driven by local needs, and decision-making is grounded in evidence and robust data gathered in local contexts. We are critically aware of the existing evidence. We attend events and participate in activities that are organised by our host communities. We respect, care for and create long-lasting friendships with our hosts. We aim to abide by local expectations around dress and custom, and if working in communities where the primary language is not our own, we are committed to learning the language. We maintain links with our hosts after the project ends and we support their future professional endeavors.

## We are committed to the working hours, professional expectations and responsibilities defined by the overall project directors. 

We typically work as part of a larger project team guided by wider goals than ours alone. We are aware of their responsibilities, we have read the necessary guidance documents, we have understood and signed the necessary insurance and risk assessment documentation, and in all cases, we respect and abide by the instructions given by the directors. This includes zero tolerance in relation to behavior that compromises the well being, equality, security or dignity of other human beings, as described below.

## We are representatives and extensions of the University of California, Riverside and its staff, and of the professional bodies to which we and our project leaders are subscribed. 

We recognize our duty of care to, and our responsibility for professionalism in, not only the communities where we work and reside, but the university and surrounding organisations to which we and our project leaders are accountable. Our behaviors reflect on these institutions and we acknowledge that our direct supervisor is (and therefore we too are) bound by the ethical and professional codes of both UC Riverside and other institutional affiliations.

Considering these obligations, you agree with the following:

- I will come to my direct supervisor the moment that I experience problems, challenges or trouble of any kind. I will keep her informed of any issues that I feel may manifest themselves in relation to myself, my teammates or affiliates while in the field. If I feel I need support beyond my direct supervisor, I will turn to the 2nd identified lead for their advice. I have already disclosed to my direct supervisor any potential matters of concern (which may include matters relating to health, psychological and physical wellbeing, security, equality, confidence, interpersonal relations, previous travel or fieldwork experiences, etc.) so that they are aware of them and can mitigate them prior to departing for - and during - fieldwork. If I have not yet disclosed such matters, I agree to do so as soon as possible. I have shared this information in confidence, with an expectation of complete privacy unless urgent medical, safety, security, or other legal intervention is required.

## We recognize that fieldwork can be intense, emotional and tiring. 

We understand that things can go wrong, that we may need to compromise, and that in exceptional circumstances, we made need to shorten or modify your work on site to help manage these circumstances. In such cases, we will have a series of conversations about how to deal with difficulties, led by your direct supervisor and/or other lead. If the difficulties are not resolved within 7 days of identification, we will consult with the university for their guidance. If it is agreed with the University that the difficulties are unresolvable in the field, we will help you to organize your safe return home.

## We have the right to a safe, secure and non-threatening working and living environment. 

We do not tolerate any form of discriminatory, abusive, aggressive, harassing, threatening, sexually- or physically-intimidating, or related problematic behaviors that compromise the wellbeing, equality, security or dignity of other human beings (whether those humans are our peers, colleagues, supervisors, collaborators, local community members or any persons at all). Our supervisors are trained in supporting those who have experienced or are experiencing harassment. They are obliged to investigate and respond to observed, implied or directly reported harassment. Considering this zero-tolerance policy, you agree to the following:

- I will not engage in behavior that compromises the wellbeing, equality, security or dignity of other human beings. I recognize that if I am implicated in such behavior I will be required to leave the project at my own expense and may be subject to criminal investigation. 

If I witness others being subjected to such behavior, I will report it immediately to my direct supervisor. If I feel I cannot speak to my direct supervisor, I will report it to the 2nd identified lead. If I feel I cannot report it to either my direct supervisor or the 2nd lead, then I will contact the [University of California, Riverside Compliance office](https://compliance.ucr.edu/investigations-complaint-resolution). 

- If I myself feel unsafe or uncomfortable, I will report it immediately to my direct supervisor. My supervisor will support me and will implement actions to keep me safe while working to stop the behavior. If I feel I cannot speak to my direct supervisor, I will report it to the 2nd identified lead. If I feel I cannot report it to either my direct supervisor or the 2nd lead, then I will contact the [University of California, Riverside Compliance office](https://compliance.ucr.edu/investigations-complaint-resolution). 

- My commitment to creating and maintaining safety and security for all extends to my online (web and social media) and mobile phone interactions, and I recognize that the process for reporting and acting on threatening online/mobile phone behaviors is the same as above.


## Important University of California, Riverside Links

- [UCR Values](https://tartansoul.ucr.edu/)
- [Ethics & Compliance Program](https://compliance.ucr.edu/ethics-compliance-program)
- [Equal Opportunity and Affirmative Action](https://titleix.ucr.edu/)
- [Discrimination, Harassment, and Retaliation Complaint and Resolution](https://fboapps.ucr.edu/policies/index.php?path=printPolicies.php&policy=650-75)
- [Standards of Conduct](https://conduct.ucr.edu/policies/standards-of-conduct)
- [Environmental Heath & Safety](https://ehs.ucr.edu/)
- [Alcohol and Drug Policy](https://fboapps.ucr.edu/policies/index.php?path=viewPolicies.php&policy=650-83)
- [Personal Relationship Policy](https://fboapps.ucr.edu/policies/index.php?path=viewPolicies.php&policy=650-74)

